exports.DICE = {
    ABILITY: {
        BLANK: 'blank.png',
        A:     'a.png',
        A1:     'a.png',
        AA:    'aa.png',
        S:     's.png',
        S1:     's.png',
        SA:    'sa.png',
        SS:    'ss.png'
    },
    BOOST: {
        BLANK:  'blank.png',
        BLANK2: 'blank.png',
        A:      'a.png',
        AA:     'aa.png',
        S:      's.png',
        SA:     'sa.png'
    },
    CHALLENGE: {
        BLANK:   'blank.png',
        F:       'f.png',
        F2:      'f.png',
        FF:      'ff.png',
        FF2:     'ff.png',
        FT:      'ft.png',
        FT2:     'ft.png',
        T:       't.png',
        T2:      't.png',
        TT:      'tt.png',
        TT2:     'tt.png',
        DESPAIR: 'despair.png'
    },
    DIFFICULTY: {
        BLANK: 'blank.png',
        F:     'f.png',
        FF:    'ff.png',
        FT:    'ft.png',
        T:     't.png',
        T2:    't.png',
        T3:    't.png',
        TT:    'tt.png'
    },
    FORCE: {
        D:   'd.png',
        D2:  'd.png',
        D3:  'd.png',
        D4:  'd.png',
        D5:  'd.png',
        D6:  'd.png',
        DD:  'dd.png',
        L:   'l.png',
        L2:  'l.png',
        LL:  'll.png',
        LL2: 'll.png',
        LL3: 'll.png'
    },
    PROFICIENCY: {
        BLANK:   'blank.png',
        S:       's.png',
        S2:      's.png',
        SA:      'sa.png',
        SA2:     'sa.png',
        SA3:     'sa.png',
        SS:      'ss.png',
        SS2:     'ss.png',
        A:       'a.png',
        AA:      'aa.png',
        AA2:     'aa.png',
        TRIUMPH: 'triumph.png'
    },
    SETBACK: {
        BLANK:  'blank.png',
        BLANK2: 'blank.png',
        F:      'f.png',
        F2:     'f.png',
        T:      't.png',
        T2:     't.png',
    },
}
